# Generated by Django 4.0.6 on 2022-07-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('number_of_peroids', models.IntegerField(default=0)),
            ],
        ),
    ]
