# Generated by Django 4.0.6 on 2022-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday')], default='monday', max_length=10),
        ),
    ]
