# Generated by Django 4.1 on 2022-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_rename_subjects_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='S2_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S3_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S4_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S5_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S6_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S7_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S8_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('number_of_peroids_on_monday', models.IntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.IntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.IntegerField(default=0)),
                ('number_of_peroids_on_friday', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='S1_Subject',
        ),
    ]
