# Generated by Django 4.1 on 2022-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_class_remove_s1_subject_number_of_peroids_on_friday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RenameField(
            model_name='s1_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s2_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s3_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s4_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s5_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s6_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s7_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='s8_subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='s1_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s2_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s3_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s4_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s5_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s6_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s7_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
        migrations.AddField(
            model_name='s8_subject',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cl', 'Computer Science:AI and Machine Learning'), ('ec_a', 'Electronics and Communication A'), ('ec_b', 'Electronics and Communication B'), ('bt', 'Biotechnology'), ('me_a', 'Mechanical'), ('me_b', 'Mechanical')], default='cs', max_length=45),
        ),
    ]
