# Generated by Django 4.1 on 2022-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0011_alter_s1_subject_number_of_peroids_on_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Science:AI and Machine Learning', 'Computer Science:AI and Machine Learning'), ('Electronics and Communication A', 'Electronics and Communication A'), ('Electronics and Communication B', 'Electronics and Communication B'), ('Biotechnology', 'Biotechnology'), ('Mechanical Engineering A', 'Mechanical Engineering A'), ('Mechanical Engineering B', 'Mechanical Engineering B')], default='cs', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('Semester 1 ', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], default='Semester 1', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='s1_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s2_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s3_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s4_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s5_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s6_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s7_subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='s8_subject',
            name='branch',
        ),
    ]
