# Generated by Django 4.1 on 2022-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0012_branch_semesters_remove_s1_subject_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=40)),
                ('number_of_peroids_on_monday', models.PositiveIntegerField(default=0)),
                ('number_of_peroids_on_tuesday', models.PositiveIntegerField(default=0)),
                ('number_of_peroids_on_wednesday', models.PositiveIntegerField(default=0)),
                ('number_of_peroids_on_thursday', models.PositiveIntegerField(default=0)),
                ('number_of_peroids_on_friday', models.PositiveIntegerField(default=0)),
                ('sub_branch', models.ManyToManyField(to='algorithm.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='S1_Subject',
        ),
        migrations.DeleteModel(
            name='S2_Subject',
        ),
        migrations.DeleteModel(
            name='S3_Subject',
        ),
        migrations.DeleteModel(
            name='S4_Subject',
        ),
        migrations.DeleteModel(
            name='S5_Subject',
        ),
        migrations.DeleteModel(
            name='S6_Subject',
        ),
        migrations.DeleteModel(
            name='S7_Subject',
        ),
        migrations.DeleteModel(
            name='S8_Subject',
        ),
    ]
