# Generated by Django 4.1 on 2022-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0013_subject_delete_s1_subject_delete_s2_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub_branch',
            new_name='subject_branch',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_semester',
            field=models.ManyToManyField(to='algorithm.semesters'),
        ),
        migrations.AlterField(
            model_name='semesters',
            name='sem',
            field=models.CharField(choices=[('Semester 1 ', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8'), ('Minors', 'Minors'), ('Honours', 'Honours')], default='Semester 1', max_length=15),
        ),
    ]
