# Generated by Django 4.1 on 2022-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0014_rename_sub_branch_subject_subject_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(default='unnamed holiday', max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_semester',
        ),
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='semesters',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
