# Generated by Django 5.0.1 on 2024-02-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0016_rename_holidays_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='holiday',
        ),
    ]
